Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,10 +58,11 @@ jobs:
           echo "::set-output name=init-stdout::${init_stdout}"
           echo "::set-output name=init-outcome::${init_outcome}"
           
+          # Disables the immediate action failure due to exit code 2 on changes detected
           set +e
           plan_stdout="$(terraform plan -no-color -detailed-exitcode)"
-          set -e
           plan_outcome=$([ "$?" == 0 ] && echo "success" || echo "failure")
+          set -e
           plan_stdout="${plan_stdout//'%'/'%25'}"
           plan_stdout="${plan_stdout//$'\n'/'%0A'}"
           plan_stdout="${plan_stdout//$'\r'/'%0D'}"
