Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,8 +46,17 @@ jobs:
           fmt_stdout="${fmt_stdout//$'\r'/'%0D'}"
           fmt_outcome=$([ "$?" == 0 ] && echo "success" || echo "failure")
           
-          echo "::set-output name=fmt-stdout::${fmt_stdout}
-          echo "::set-output name=fmt-outcome::${fmt_outcome}
+          echo "::set-output name=fmt-stdout::${fmt_stdout}"
+          echo "::set-output name=fmt-outcome::${fmt_outcome}"
+          
+          init_stdout="$(terraform init)"
+          init_stdout="${init_stdout//'%'/'%25'}"
+          init_stdout="${init_stdout//$'\n'/'%0A'}"
+          init_stdout="${init_stdout//$'\r'/'%0D'}"
+          init_outcome=$([ "$?" == 0 ] && echo "success" || echo "failure")
+          
+          echo "::set-output name=init-stdout::${init_stdout}"
+          echo "::set-output name=init-outcome::${init_outcome}"
           
           plan_stdout="$(terraform plan -no-color -detailed-exitcode)"
           plan_stdout="${plan_stdout//'%'/'%25'}"
