Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,20 +40,20 @@ jobs:
         # Follows tips from:
         # https://github.community/t/set-output-truncates-multiline-strings/16852/5
         run: |
-          fmt-stdout="$(terraform fmt)"
-          fmt-stdout="${fmt-stdout//'%'/'%25'}"
-          fmt-stdout="${fmt-stdout//$'\n'/'%0A'}"
-          fmt-stdout="${fmt-stdout//$'\r'/'%0D'}"
-          fmt-outcome=$([ "$?" == 0 ] && echo "success" || echo "failure")
+          fmt_stdout="$(terraform fmt)"
+          fmt_stdout="${fmt_stdout//'%'/'%25'}"
+          fmt_stdout="${fmt_stdout//$'\n'/'%0A'}"
+          fmt_stdout="${fmt_stdout//$'\r'/'%0D'}"
+          fmt_outcome=$([ "$?" == 0 ] && echo "success" || echo "failure")
           
-          echo "::set-output name=fmt-stdout::${fmt-stdout}
-          echo "::set-output name=fmt-outcome::${fmt-outcome}
+          echo "::set-output name=fmt-stdout::${fmt_stdout}
+          echo "::set-output name=fmt-outcome::${fmt_outcome}
           
-          plan-stdout="$(terraform plan -no-color -detailed-exitcode)"
-          plan-stdout="${plan-stdout//'%'/'%25'}"
-          plan-stdout="${plan-stdout//$'\n'/'%0A'}"
-          plan-stdout="${plan-stdout//$'\r'/'%0D'}"
-          echo "::set-output name=plan-stdout::${plan-stdout}"
+          plan_stdout="$(terraform plan -no-color -detailed-exitcode)"
+          plan_stdout="${plan_stdout//'%'/'%25'}"
+          plan_stdout="${plan_stdout//$'\n'/'%0A'}"
+          plan_stdout="${plan_stdout//$'\r'/'%0D'}"
+          echo "::set-output name=plan-stdout::${plan_stdout}"
         continue-on-error: true
       - uses: actions/github-script@0.9.0
         if: github.event_name == 'pull_request'
@@ -61,11 +61,11 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const output = `#### \`${{ matrix.dir }}\`
-            #### terraform fmt: \`${{ steps.plan.outputs.fmt-outcome }}\`
+            #### terraform fmt: \`${{ steps.plan.outputs.fmt_outcome }}\`
             <details><summary>Show fmt</summary>
 
             \`\`\`
-            ${{ steps.plan.outputs.fmt-stdout }}
+            ${{ steps.plan.outputs.fmt_stdout }}
             \`\`\`
 
             </details>
